### ISSUE TITLE
PRACTICA_DE_EJERCICIOS_BASICOS

### ISSUE THREAD

**Issue by Eduardo21620095** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-Eduardo21620095#1]
[EJERCICIOS_EDUARDO_TOMAS_FERIA_ORTIZ_1AS.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-operaciones-basicas-Eduardo21620095/files/7174819/EJERCICIOS_EDUARDO_TOMAS_FERIA_ORTIZ_1AS.pdf)

**Comment by Arlet04** [comment]
Portada (excelente) contiene todos los datos requeridos 25 puntos
Procedimiento  (suficiente) contiene suficientes ejemplos pero no basta ya que faltó explicar el procedimiento de cada uno de ellos  17 puntos 
Figuras, ilustraciones y fotografías (excelente) muestra suficientes fotografías 25 puntos
Resultados y conclusiones (Bueno) Le falta ampliación a resultados y al mismo tiempo conclusión 20 puntos
Total: 87/100
calificación: 17.4% / 20%
calificado por: Jeanette Arlet Salazar Nicolás

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
